title: "Michael Back, PhD"
description: "Postdoctoral Scholar"
theme: minima
markdown: kramdown

# Navigation links
header_pages:
  - index.md
  - research.md
  - publications.md
  - cv.md
  - contact.md
